services:
  backend:
    build: Backend
    container_name: bb6_backend
    ports:
      - "5000:8080"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: bb6_sql_server2022
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=A&VeryComplex123Password
